// metronic-613/theme/react/demo2/src/_metronic/layout/footer/Footer.js
/* eslint-disable react/jsx-no-target-blank */
/* eslint-disable no-script-url */
/* eslint-disable jsx-a11y/anchor-is-valid */
import React from "react";
import { Link } from "react-router-dom";
import objectPath from "object-path";
import { connect } from "react-redux";
import { toAbsoluteUrl } from "../../utils/utils";

class Footer extends React.Component {
  render() {
    const today = new Date().getFullYear();
    const { footerSelfLayoutIsExtended, htmlClassService } = this.props;
    const footerClasses = htmlClassService.classes.footer.join(" ");
    const footerContainerClasses = htmlClassService.classes.footer_container.join(" ");
    return (
        <div
          className={`kt-footer ${footerClasses} kt-grid__item`}
          id="kt_footer"
        >
          {footerSelfLayoutIsExtended && (
          <div className="kt-footer__top">
            <div className={`kt-container ${footerContainerClasses}`}>
              <div className="row">
                <div className="col-lg-4">
                  <div className="kt-footer__section">
                    <h3 className="kt-footer__title">About</h3>
                    <div className="kt-footer__content">
                      Whatever method you chosse,these nine will
                      make you re-think theway you craft healines
                      Why? Because they all have points in that are
                      worth from a point of view.
                    </div>
                  </div>
                </div>
                <div className="col-lg-4">
                  <div className="kt-footer__section">
                    <h3 className="kt-footer__title">Quick Links</h3>
                    <div className="kt-footer__content">
                      <div className="kt-footer__nav">
                        <div className="kt-footer__nav-section">
                          <a href="#">General Reports</a>
                          <a href="#">Dashboart Widgets</a>
                          <a href="#">Custom Pages</a>
                        </div>
                        <div className="kt-footer__nav-section">
                          <a href="#">User Setting</a>
                          <a href="#">Custom Pages</a>
                          <a href="#">Intranet Settings</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="col-lg-4">
                  <div className="kt-footer__section">
                    <h3 className="kt-footer__title">Get In Touch</h3>
                    <div className="kt-footer__content">
                      <form action="" className="kt-footer__subscribe">
                        <div className="input-group">
                          <input type="text" className="form-control" placeholder="Enter Your Email" />
                            <div className="input-group-append">
                              <button className="btn btn-brand" type="button">Join</button>
                            </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          )}
          <div className="kt-footer__bottom">
            <div className={`kt-container ${footerContainerClasses}`}>
              <div className="kt-footer__wrapper">
                <div className="kt-footer__logo">
                  <Link to={"/"}>
                    <img alt="Logo" src={toAbsoluteUrl("/media/logos/logo-2-sm.png")} />
                  </Link>
                  <div className="kt-footer__copyright">
                    {today}&nbsp;&copy;&nbsp;
                    <a href="http://keenthemes.com/metronic" target="_blank">Keenthemes</a>
                  </div>
                </div>
                <div className="kt-footer__menu">
                  <a href="http://keenthemes.com/metronic" target="_blank">Purchase License</a>
                  <a href="http://keenthemes.com/metronic" target="_blank">Team</a>
                  <a href="http://keenthemes.com/metronic" target="_blank">Contact</a>
                </div>
              </div>
            </div>
          </div>
        </div>
    );
  }
}

const mapStateToProps = store => ({
  footerSelfLayoutIsExtended: objectPath.get(store.builder.layoutConfig, "footer.self.layout") === "extended"
});

export default connect(mapStateToProps)(Footer);

// metronic-613/theme/angular/demo2/src/app/views/theme/footer/footer.component.ts
// Angular
import { Component, OnInit } from '@angular/core';
// Layout
import { LayoutConfigService } from '../../../core/_base/layout';
// Object-Path
import * as objectPath from 'object-path';

@Component({
	selector: 'kt-footer',
	templateUrl: './footer.component.html',
})
export class FooterComponent implements OnInit {
	// Public properties
	today: number = Date.now();
	fluid: boolean;

	/**
	 * Component constructor
	 *
	 * @param layoutConfigService: LayouConfigService
	 */
	constructor(private layoutConfigService: LayoutConfigService) {
	}

	/**
	 * @ Lifecycle sequences => https://angular.io/guide/lifecycle-hooks
	 */

	/**
	 * On init
	 */
	ngOnInit(): void {
		const config = this.layoutConfigService.getConfig();

		// footer width fluid
		this.fluid = objectPath.get(config, 'footer.self.width') === 'fluid';
	}
}

<!-- begin:: Footer -->
<div class="kt-footer kt-footer--extended kt-grid__item" id="kt_footer">
	<div class="kt-footer__top">
		<div class="kt-container" [ngClass]="{'kt-container--fluid': fluid}">
			<div class="row">
				<div class="col-lg-4">
					<div class="kt-footer__section">
						<h3 class="kt-footer__title">About</h3>
						<div class="kt-footer__content">
							Whatever method you chosse,these nine will
							make you re-think theway you craft healines
							Why? Because they all have points in that are
							worth from a point of view.
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="kt-footer__section">
						<h3 class="kt-footer__title">Quick Links</h3>
						<div class="kt-footer__content">
							<div class="kt-footer__nav">
								<div class="kt-footer__nav-section">
									<a href="javascript:;">General Reports</a>
									<a href="javascript:;">Dashboart Widgets</a>
									<a href="javascript:;">Custom Pages</a>
								</div>
								<div class="kt-footer__nav-section">
									<a href="javascript:;">User Setting</a>
									<a href="javascript:;">Custom Pages</a>
									<a href="javascript:;">Intranet Settings</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="kt-footer__section">
						<h3 class="kt-footer__title">Get In Touch</h3>
						<div class="kt-footer__content">
							<form action="" class="kt-footer__subscribe">
								<div class="input-group">
									<input type="text" class="form-control" placeholder="Enter Your Email">
									<div class="input-group-append">
										<button class="btn btn-info" type="button">Join</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="kt-footer__bottom">
		<div class="kt-container" [ngClass]="{'kt-container--fluid': fluid}">
			<div class="kt-footer__wrapper">
				<div class="kt-footer__logo">
					<a href="/">
						<img alt="Logo" src="./assets/media/logos/logo-2-sm.png">
					</a>
					<div class="kt-footer__copyright">
						{{today | date:'yyyy'}}&nbsp;©&nbsp;
						<a href="http://keenthemes.com/metronic" target="_blank">Keenthemes</a>
					</div>
				</div>
				<div class="kt-footer__menu">
					<a href="http://keenthemes.com/metronic" target="_blank">Purchase Lisence</a>
					<a href="http://keenthemes.com/metronic" target="_blank">Team</a>
					<a href="http://keenthemes.com/metronic" target="_blank">Contact</a>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end:: Footer -->
